#开启所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#配置Druid数据源
spring:
  datasource:
    username: root
    password: 445221
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.185.88:3306/cloud-demo-1?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#配置Mybatis的Mapper映射文件路径
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

#配置dubbo服务注册地址以及要注册的服务所在的包路径,并设置5s超时
dubbo:
  application:
    name: mallService
  registry:
    address: zookeeper://112.74.185.88:2181
  scan:
    base-packages: com.scau.mall.service
  consumer:
    timeout: 5000