
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  thymeleaf:
    prefix: /WEB-INF/template

dubbo:
  application:
    name: mallWeb
  registry:
    address: zookeeper://112.74.185.88:2181
